### ISSUE TITLE
Issue running test set eval

### ISSUE THREAD

**Issue by benleetownsend** [applicaai/kleister-nda#1]
Hi, firstly thanks for putting together this interesting dataset.

I believe I have figured out how to run the metrics for the test set by taking a fork of the repo - pushing up results and then running
```./geval -S -t test-A/```
However I am prompted for a token which I cannot find in the repo, if I pass no value for the token I get timeouts.

**Comment by Dod-o** [comment]
hi, I can't find the repo of Kleister in Gonito, can you send me a link? Thanks!

**Comment by tstanislawek** [comment]
@Dod-o , @benleetownsend 

Hi, sorry for late answer. I have put `expected.tsv` file for test set, so you could easily evaluate your solutions.

**Comment by benleetownsend** [comment]
Thanks @tstanislawek that is really helpful.
