### ISSUE TITLE
Annotation Tool

### ISSUE THREAD

**Issue by fatemerhmi** [applicaai/kleister-nda#5]
Hello, 

Would you please let me know (or add to the `README`) about the annotation tool that was used and if it is available publicly? 

Thank you

**Comment by tstanislawek** [comment]
Hello @fatemerhmi ,
Sorry, but we were using our internal annotation tool so it's impossible to make it publicly available 

Regards,
Tomasz

**Comment by fatemerhmi** [comment]
Thanks for letting me know.
